services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  api-gateway:
    image: connectify-backend/api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - room-service
      - video-chat-service
    networks:
      - app-network

  auth-service:
    image: connectify-backend/auth-service
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  room-service:
    image: connectify-backend/room-service
    ports:
      - "5002:5002"
    networks:
      - app-network

  video-chat-service:
    image: connectify-backend/video-chat-service
    ports:
      - "5003:5003"
    networks:
      - app-network

networks:
  app-network:
